### ISSUE TITLE
Symlinks cause an exception when formatting a workspace

### ISSUE THREAD

**Issue by theor** [dotnet/format#1011]
Hi,

We sometimes have symlinks in our repos, which breaks the formatter:

```
Unhandled exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\<path to symlink folder>'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.FileSystemInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Microsoft.Extensions.FileSystemGlobbing.Abstractions.DirectoryInfoWrapper.EnumerateFileSystemInfos()+MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Microsoft.Extensions.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Extensions.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Extensions.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Extensions.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Extensions.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Extensions.FileSystemGlobbing.Internal.MatcherContext.Execute()
   at Microsoft.Extensions.FileSystemGlobbing.Matcher.Execute(DirectoryInfoBase directoryInfo)
   at Microsoft.Extensions.FileSystemGlobbing.MatcherExtensions.GetResultsInFullPath(Matcher matcher, String directoryPath)
   at Microsoft.CodeAnalysis.Tools.Utilities.SourceFileMatcher.GetResultsInFullPath(String directoryPath) in /_/src/Utilities/SourceFileMatcher.cs:line 41
   at Microsoft.CodeAnalysis.Tools.Workspaces.FolderWorkspace.FolderSolutionLoader.GetMatchingFilePaths(String folderPath, SourceFileMatcher fileMatcher) in /_/src/Workspaces/FolderWorkspace_FolderSolutionLoader.cs:line 54
   at Microsoft.CodeAnalysis.Tools.Workspaces.FolderWorkspace.FolderSolutionLoader.LoadSolutionInfo(String folderPath, SourceFileMatcher fileMatcher) in /_/src/Workspaces/FolderWorkspace_FolderSolutionLoader.cs:line 18
   at Microsoft.CodeAnalysis.Tools.Workspaces.FolderWorkspace.OpenFolder(String folderPath, SourceFileMatcher fileMatcher) in /_/src/Workspaces/FolderWorkspace.cs:line 41
   at Microsoft.CodeAnalysis.Tools.CodeFormatter.FormatWorkspaceAsync(FormatOptions formatOptions, ILogger logger, CancellationToken cancellationToken, Boolean createBinaryLog) in /_/src/CodeFormatter.cs:line 45
   at Microsoft.CodeAnalysis.Tools.Program.Run(String workspace, Boolean folder, Boolean fixWhitespace, String fixStyle, String fixAnalyzers, String verbosity, Boolean check, String[] include, String[] exclude, String report, Boolean includeGenerated, IConsole console) in /_/src/Program.cs:line 173
   at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__21_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseVersionOption>b__0>d.MoveNext()--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__22_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__20_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__11_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

this is on windows 10, dotnet 5.0.102, format version 5.0.211001+10cb1372c1e5ea38316d1e77c4682b3bf950870f

**Comment by jmarolf** [comment]
huh, @JoeRobich I think this should just be handled by `Microsoft.Extensions.FileSystemGlobbing.Matcher` right? I assume this is a bug on them? the .NET 5 runtime should be fully capable of resolving the targets of hard links on windows.

**Comment by JoeRobich** [comment]
> huh, @JoeRobich I think this should just be handled by `Microsoft.Extensions.FileSystemGlobbing.Matcher` right? I assume this is a bug on them? the .NET 5 runtime should be fully capable of resolving the targets of hard links on windows.

@Jozkee, thanks for being helpful with other FileSystemGlobbing issues. Do you have any insight on this issue?
