### ISSUE TITLE
System.Collections.Generic.KeyNotFoundException: The given key 'MissingCases' was not present in the dictionary.

### ISSUE THREAD

**Issue by marek-safar** [dotnet/format#1023]
dotnet-tool crashes when running code fixers. This is most likely not a problem in dotnet tool but it'd be useful to show which analyzer/fixer crashed to be able to work around the problem.

```
  Running 1 analyzers on ILLink.RoslynAnalyzer.Tests.
Unhandled exception: System.Collections.Generic.KeyNotFoundException: The given key 'MissingCases' was not present in the dictionary.
   at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key)
   at Microsoft.CodeAnalysis.PopulateSwitch.AbstractPopulateSwitchCodeFixProvider`4.RegisterCodeFixesAsync(CodeFixContext context)
   at Microsoft.CodeAnalysis.Tools.Analyzers.SolutionCodeFixApplier.ApplyCodeFixesAsync(Solution solution, CodeAnalysisResult result, CodeFixProvider codeFix, String diagnosticId, ILogger logger, CancellationToken cancellationToken) in /_/src/Analyzers/SolutionCodeFixApplier.cs:line 60
   at Microsoft.CodeAnalysis.Tools.Analyzers.AnalyzerFormatter.FixDiagnosticsAsync(Solution solution, ImmutableDictionary`2 projectAnalyzers, ImmutableArray`1 allFixers, ImmutableDictionary`2 projectDiagnostics, ImmutableHashSet`1 formattablePaths, DiagnosticSeverity severity, Boolean includeCompilerDiagnostics, ILogger logger, CancellationToken cancellationToken) in /_/src/Analyzers/AnalyzerFormatter.cs:line 228
   at Microsoft.CodeAnalysis.Tools.Analyzers.AnalyzerFormatter.FormatAsync(Solution solution, ImmutableArray`1 formattableDocuments, FormatOptions formatOptions, ILogger logger, List`1 formattedFiles, CancellationToken cancellationToken) in /_/src/Analyzers/AnalyzerFormatter.cs:line 100
   at Microsoft.CodeAnalysis.Tools.CodeFormatter.RunCodeFormattersAsync(Solution solution, ImmutableArray`1 formattableDocuments, FormatOptions formatOptions, ILogger logger, List`1 formattedFiles, CancellationToken cancellationToken) in /_/src/CodeFormatter.cs:line 141
   at Microsoft.CodeAnalysis.Tools.CodeFormatter.FormatWorkspaceAsync(FormatOptions formatOptions, ILogger logger, CancellationToken cancellationToken, Boolean createBinaryLog) in /_/src/CodeFormatter.cs:line 71
   at Microsoft.CodeAnalysis.Tools.Program.Run(String workspace, Boolean folder, Boolean fixWhitespace, String fixStyle, String fixAnalyzers, String verbosity, Boolean check, String[] include, String[] exclude, String report, Boolean includeGenerated, IConsole console) in /_/src/Program.cs:line 173
   at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__21_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__22_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__20_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__11_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by jmarolf** [comment]
@JoeRobich how do you feel about printing:

```
"CSharpPopulateSwitchStatementCodeFixProvider" from "Microsoft.CodeAnalysis.CSharp.CodeStyle.Fixes" threw the following exception:
  System.Collections.Generic.KeyNotFoundException: The given key 'MissingCases' was not present in the dictionary.
call stack:
   at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key)
   at Microsoft.CodeAnalysis.PopulateSwitch.AbstractPopulateSwitchCodeFixProvider`4.RegisterCodeFixesAsync(CodeFixContext context)
   at Microsoft.CodeAnalysis.Tools.Analyzers.SolutionCodeFixApplier.ApplyCodeFixesAsync(Solution solution, CodeAnalysisResult result, CodeFixProvider codeFix, String diagnosticId, ILogger logger, CancellationToken cancellationToken) in /_/src/Analyzers/SolutionCodeFixApplier.cs:line 60
   at Microsoft.CodeAnalysis.Tools.Analyzers.AnalyzerFormatter.FixDiagnosticsAsync(Solution solution, ImmutableDictionary`2 projectAnalyzers, ImmutableArray`1 allFixers, ImmutableDictionary`2 projectDiagnostics, ImmutableHashSet`1 formattablePaths, DiagnosticSeverity severity, Boolean includeCompilerDiagnostics, ILogger logger, CancellationToken cancellationToken) in /_/src/Analyzers/AnalyzerFormatter.cs:line 228
   at Microsoft.CodeAnalysis.Tools.Analyzers.AnalyzerFormatter.FormatAsync(Solution solution, ImmutableArray`1 formattableDocuments, FormatOptions formatOptions, ILogger logger, List`1 formattedFiles, CancellationToken cancellationToken) in /_/src/Analyzers/AnalyzerFormatter.cs:line 100
   at Microsoft.CodeAnalysis.Tools.CodeFormatter.RunCodeFormattersAsync(Solution solution, ImmutableArray`1 formattableDocuments, FormatOptions formatOptions, ILogger logger, List`1 formattedFiles, CancellationToken cancellationToken) in /_/src/CodeFormatter.cs:line 141
   at Microsoft.CodeAnalysis.Tools.CodeFormatter.FormatWorkspaceAsync(FormatOptions formatOptions, ILogger logger, CancellationToken cancellationToken, Boolean createBinaryLog) in /_/src/CodeFormatter.cs:line 71
   at Microsoft.CodeAnalysis.Tools.Program.Run(String workspace, Boolean folder, Boolean fixWhitespace, String fixStyle, String fixAnalyzers, String verbosity, Boolean check, String[] include, String[] exclude, String report, Boolean includeGenerated, IConsole console) in /_/src/Program.cs:line 173
   at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__21_0>d.MoveNext()
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseVersionOption>b__0>d.MoveNext()
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseTypoCorrections>b__0>d.MoveNext()
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__22_0>d.MoveNext()
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__20_0>d.MoveNext()
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__11_0>d.MoveNext()
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by jmarolf** [comment]
never mind, lets just keep the existing message but expand the `try` block
