### ISSUE TITLE
add --exclude-diagnostics option

### ISSUE THREAD

**Issue by jmarolf** [dotnet/format#1495]
Today we have `--diagnostics` to list out specific diagnostics that should be fixed when running `dotnet format`. If, in the course of human events, you want to run  `dotnet format` but _exclude_ a single diagnostic from the set there is no convenient way to do so.

I propose adding `--exclude-diagnostics` which would make this scenario easier.

**Comment by tebeco** [comment]
Adding a bit of context to this one.
This comes up after a discussion on `diagnostic` that could apply, for example `[Obsolete]`:

Before:
```cs
public void Caller() => Callee();

[Obsolete]
public void Callee() {}
```
after `dotnet format`:
```diff
+ [Obsolete]
  public void Caller() => Callee();

  [Obsolete]
  public void Callee() {}
```

As much as `Obsolete` should be fixed, sometime you want to let the Warning visible, especially the `Obsolete` one as a fix is not available yet
(but that is just a single example)

goal:
* do not `#pragma disable warning CSxxxxx`
* use `dotnet format` with all it default behavior, except maybe one or two `diagnostics`

**Comment by Vandersteen** [comment]
Did you find any solution for this ?
I'm hitting the same problem here and it's kind of blocking us from using dotnet format

**Comment by bitblitz** [comment]
Curious why this issue is (still) open...

I see an `--exclude-diagnostics` option.  However, I can't get it to actually work:
```
C:\Program Files>dotnet format --help
Description:
  Formats code to match editorconfig settings.

Usage:
  dotnet-format [<The project or solution file to operate on. If a file is not specified, the command will search the current directory for one.>] [command] [options]

Arguments:
  <The project or solution file to operate on. If a file is not specified, the   The project or solution file to operate on. If a file is not specified, the command will
  command will search the current directory for one.>                            search the current directory for one. [default: C:\Program Files\]

Options:
  --diagnostics <diagnostics>                                              A space separated list of diagnostic ids to use as a filter when fixing code style or 3rd party
                                                                           issues. []
  --exclude-diagnostics <exclude-diagnostics>                              A space separated list of diagnostic ids to ignore when fixing code style or 3rd party issues.
                                                                           []
...
```

I get this:
```
C:\dev\TSS.MSR>dotnet format style --report x.json -v d --exclude-diagnostics IDE0049 x\x.sln
Unhandled exception: System.IO.FileNotFoundException: Could not find a MSBuild project file or solution file in 'C:\dev\TSS.MSR\'. Specify which to use with the <workspace> argument.
   at Microsoft.CodeAnalysis.Tools.Workspaces.MSBuildWorkspaceFinder.FindWorkspace(String searchDirectory, String workspacePath)
   at Microsoft.CodeAnalysis.Tools.Workspaces.MSBuildWorkspaceFinder.FindWorkspace(String searchDirectory, String workspacePath)
   at Microsoft.CodeAnalysis.Tools.FormatCommandCommon.ParseWorkspaceOptions(ParseResult parseResult, FormatOptions formatOptions)
   at Microsoft.CodeAnalysis.Tools.Commands.FormatStyleCommand.FormatStyleHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass21_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass18_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__17_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass15_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__4_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass7_0.<<UseExceptionHandler>b__0>d.MoveNext()
   ```
   
If I don't include the ``--exclude-diagnostics` option, then the command works - but applies formatting I don't want...

So, what's the actual status on `--exclude-diagnostics`?

**Comment by JoeRobich** [comment]
> C:\dev\TSS.MSR>dotnet format style --report x.json -v d --exclude-diagnostics IDE0049 x\x.sln

It is likely interpretting the `x\x.sln` as a diagnostic id. Try moving the solution argument to the front of the options.
