### ISSUE TITLE
`dotnet format` results in `Unhandled exception: System.Exception: Restore operation failed.`

### ISSUE THREAD

**Issue by bruno-garcia** [dotnet/format#1510]
```
Tool 'dotnet-format' (version '5.1.250801') was successfully installed.
```
Running on GitHub actions, `ubuntu-latest`. Started failing since yesterday, so possibly a .NET version update on the GH hosted agent images.

```
Unhandled exception: System.Exception: Restore operation failed.
   at Microsoft.CodeAnalysis.Tools.CodeFormatter.OpenMSBuildWorkspaceAsync(String solutionOrProjectPath, WorkspaceType workspaceType, Boolean noRestore, Boolean requiresSemantics, String binaryLogPath, Boolean logWorkspaceWarnings, ILogger logger, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Tools.CodeFormatter.FormatWorkspaceAsync(FormatOptions formatOptions, ILogger logger, CancellationToken cancellationToken, String binaryLogPath)
   at Microsoft.CodeAnalysis.Tools.FormatCommandCommon.FormatAsync(FormatOptions formatOptions, ILogger`1 logger, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Tools.Commands.RootFormatCommand.FormatCommandDefaultHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass27_0.<<UseVersionOption>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
Error: Process completed with exit code 1.
```

For reference, our workflow is: https://github.com/getsentry/sentry-unity/blob/248ca0c4d7ddf6d24185bad92825d036795182b6/.github/workflows/format-code.yml#L24-L26

Related to https://github.com/dotnet/format/issues/1248

**Comment by JoeRobich** [comment]
@bruno-garcia dotnet-format now ships in the .NET 6 SDK. Invoking `dotnet format` with a space instead of a hyphen will run the 6.x build of dotnet-format. If you want to retain the same behavior as 5.x, you would want to invoke the `dotnet whitespace` subcommand. See https://github.com/dotnet/format/issues/1268 for more details.

**Comment by bruno-garcia** [comment]
Thanks for clarifying @JoeRobich

**Comment by bruno-garcia** [comment]
I'm reopening because I've remove the dotnet install command, gave it the solution as an argument and continues to crash:

https://github.com/getsentry/sentry-unity/pull/545/files

I can't repro locally (it does restore and formats locally) so running out of ideas

**Comment by bruno-garcia** [comment]
Oh, I think it's submodule related

**Comment by bruno-garcia** [comment]
Yeah, out of ideas why this is failing. Any pointers appreciated: https://github.com/getsentry/sentry-unity/runs/5060648504?check_suite_focus=true

**Comment by JoeRobich** [comment]
When running analyzers we attempt to restore the solution or project that is being formatted. This is because semantic information would be incomplete without having nuget packages downloaded and available to include in the compilation. In 6.x we started running the style and 3rd party analysis by default. This is why it is attempting a restore.

Running `dotnet format` locally I can see the error is that the build targets are requiring that Unity be installed.

```console
dotnet format -v diag
  The dotnet runtime version is '6.0.0'.
  The dotnet CLI version is '6.0.100'.
  Using MSBuild.exe located in '/usr/local/share/dotnet/sdk/6.0.100/'.
  Formatting code files in workspace '/Users/joeyrobichaud/Source/sentry-unity/Sentry.Unity.sln'.
  Loading workspace.
  /Users/joeyrobichaud/Source/sentry-unity/Directory.Build.targets(74,5): error : UnityRoot not found. Ensure Unity is installed. [/Users/joeyrobichaud/Source/sentry-unity/src/Sentry.Unity.Editor/Sentry.Unity.Editor.csproj]
```

To keep the previous behavior of only performing whitespace formatting you can run `dotnet format whitespace`.

**Comment by bruno-garcia** [comment]
Sounds good, thanks for the details
