### ISSUE TITLE
Unhandled exception: System.Exception: Restore operation failed.

### ISSUE THREAD

**Issue by trampster** [dotnet/format#1899]
The below exception occurred in our ci when running dotnet format:

`dotnet format --verify-no-changes`

> Unhandled exception: System.Exception: Restore operation failed.
>    at Microsoft.CodeAnalysis.Tools.CodeFormatter.OpenMSBuildWorkspaceAsync(String solutionOrProjectPath, WorkspaceType workspaceType, Boolean noRestore, Boolean requiresSemantics, String binaryLogPath, Boolean logWorkspaceWarnings, ILogger logger, CancellationToken cancellationToken)
>    at Microsoft.CodeAnalysis.Tools.CodeFormatter.FormatWorkspaceAsync(FormatOptions formatOptions, ILogger logger, CancellationToken cancellationToken, String binaryLogPath)
>    at Microsoft.CodeAnalysis.Tools.FormatCommandCommon.FormatAsync(FormatOptions formatOptions, ILogger`1 logger, CancellationToken cancellationToken)
>    at Microsoft.CodeAnalysis.Tools.Commands.RootFormatCommand.FormatCommandDefaultHandler.InvokeAsync(InvocationContext context)
>    at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
> --- End of stack trace from previous location ---
>    at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseErrorReporting>b__0>d.MoveNext()
> --- End of stack trace from previous location ---
>    at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseHelp>b__0>d.MoveNext()
> --- End of stack trace from previous location ---
>    at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass21_0.<<UseVersionOption>b__0>d.MoveNext()
> --- End of stack trace from previous location ---
>    at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass18_0.<<UseTypoCorrections>b__0>d.MoveNext()
> --- End of stack trace from previous location ---
>    at System.CommandLine.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__17_0>d.MoveNext()
> --- End of stack trace from previous location ---
>    at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass15_0.<<UseParseDirective>b__0>d.MoveNext()
> --- End of stack trace from previous location ---
>    at System.CommandLine.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__4_0>d.MoveNext()
> --- End of stack trace from previous location ---
>    at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass7_0.<<UseExceptionHandler>b__0>d.MoveNext()

This exception doesn't really tell us anything. It uses System.Exception rather than a more specific type. And the message "Restore operation failed" doesn't tell us why it failed/what specifically went wrong when doing the restore operation.

**Comment by trampster** [comment]
It looks like PerformRestoreAsync is the issue, it doesn't capture the stdout/stderr of dotnet restore. So doesn't know what the issue was.
