### ISSUE TITLE
Error Changing document properties is not supported

### ISSUE THREAD

**Issue by EngRajabi** [dotnet/format#2192]
I use dotnet format. Now I have the following error
Changing document properties is not supported
I even ran with this command, but the file that causes the error does not tell me where exactly it is.
I execute this command
dotnet format -v d --no-restore
I get this error
Unhandled exception: System.NotSupportedException: Changing document properties is not supported
    at Microsoft.CodeAnalysis.Workspace.CheckAllowedProjectChanges(ProjectChanges projectChanges)
    at Microsoft.CodeAnalysis.Workspace.CheckAllowedSolutionChanges(SolutionChanges solutionChanges)
    at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution, IProgressTracker progressTracker)
    at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.TryApplyChanges(Solution newSolution, IProgressTracker progressTracker)
    at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.TryApplyChanges(Solution newSolution)
    at Microsoft.CodeAnalysis.Tools.CodeFormatter.FormatWorkspaceAsync(FormatOptions formatOptions, ILogger logger, CancellationToken cancellationToken, String binaryLogPath)
    at Microsoft.CodeAnalysis.Tools.FormatCommandCommon.FormatAsync(FormatOptions formatOptions, ILogger`1 logger, CancellationToken cancellationToken)
    at Microsoft.CodeAnalysis.Tools.Commands.RootFormatCommand.FormatCommandDefaultHandler.InvokeAsync(ParseResult parseResult, CancellationToken cancellationToken)
    at System.CommandLine.Invocation.InvocationPipeline.InvokeAsync(ParseResult parseResult, CancellationToken cancellationToken)

**Comment by NikiforovAll** [comment]
Same for me running:

`dotnet format --diagnostics IDE0130  --severity info`

**Comment by NikiforovAll** [comment]
ref: #1623

**Comment by dylanmorroll** [comment]
Hey so I encountered this error when there was a file whose namespace didn't match the folder it was in, once I changed the namespace this error went away

**Comment by nathanpovo** [comment]
Based on @TeaDrinkingProgrammer 's [comment](https://github.com/dotnet/format/issues/1623#issuecomment-2063431658) in #1623, the workaround is to exclude the `IDE0130` diagnostic using `--exclude-diagnostics IDE0130`. The final command becomes something like this:

```bash
dotnet format --exclude-diagnostics IDE0130
```

The `dotnet format` command doesn't provide enough information (even if the verbosity is set to `diagnostic`) which makes it difficult to understand what is causing the issue.

Tested on dotnet SDK version `10.0.101`.
