### ISSUE TITLE
Format tool ends in error

### ISSUE THREAD

**Issue by bishopsmove** [dotnet/format#421]
Recently added format tool (v 3.1.37601) had been working in our solution workflow on a testing basis without issue for over a week, until this error showed up half-way through a build run:

```
Unhandled exception: System.AggregateException: One or more errors occurred. (Specified argument was out of the range of valid values.
Parameter name: start) ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: start
   at Microsoft.CodeAnalysis.Text.TextSpan..ctor(Int32 start, Int32 length)
   at Microsoft.CodeAnalysis.Text.ChangedText.Merge(ImmutableArray`1 oldChanges, ImmutableArray`1 newChanges)
   at Microsoft.CodeAnalysis.Text.ChangedText.Merge(IReadOnlyList`1 changeSets)
   at Microsoft.CodeAnalysis.Text.ChangedText.GetChangeRanges(SourceText oldText)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.WithChangedText(SourceText newText)
   at Microsoft.CodeAnalysis.DocumentState.IncrementallyParse(TextAndVersion newTextAndVersion, TreeAndVersion oldTreeAndVersion, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.DocumentState.IncrementallyParseTreeAsync(ValueSource`1 oldTreeSource, ValueSource`1 newTextSource, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.CodeAnalysis.DocumentState.GetSyntaxTreeAsync(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Document.GetTextChangesAsync(Document oldDocument, CancellationToken cancellationToken)
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult_CanCallOnBackground[T](Task`1 task, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Workspace.ApplyChangedDocument(ProjectChanges projectChanges, DocumentId documentId)
   at Microsoft.CodeAnalysis.Workspace.ApplyProjectChanges(ProjectChanges projectChanges)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.ApplyProjectChanges(ProjectChanges projectChanges)
   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution, IProgressTracker progressTracker)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.TryApplyChanges(Solution newSolution, IProgressTracker progressTracker)
   at Microsoft.CodeAnalysis.Tools.CodeFormatter.FormatWorkspaceAsync(FormatOptions options, ILogger logger, CancellationToken cancellationToken) in /_/src/CodeFormatter.cs:line 88
   at Microsoft.CodeAnalysis.Tools.Program.Run(String workspace, String verbosity, Boolean dryRun, Boolean check, String files, IConsole console) in /_/src/Program.cs:line 99
   at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass3_0.<<InvokeAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseParseErrorReporting>b__16_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass3_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseSuggestDirective>b__7_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseDebugDirective>b__4_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseHelp>b__14_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseParseDirective>b__6_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<RegisterWithDotnetSuggest>b__17_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseExceptionHandler>b__5_0>d.MoveNext()
---> (Inner Exception #0) System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: start
   at Microsoft.CodeAnalysis.Text.TextSpan..ctor(Int32 start, Int32 length)
   at Microsoft.CodeAnalysis.Text.ChangedText.Merge(ImmutableArray`1 oldChanges, ImmutableArray`1 newChanges)
   at Microsoft.CodeAnalysis.Text.ChangedText.Merge(IReadOnlyList`1 changeSets)
   at Microsoft.CodeAnalysis.Text.ChangedText.GetChangeRanges(SourceText oldText)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.WithChangedText(SourceText newText)
   at Microsoft.CodeAnalysis.DocumentState.IncrementallyParse(TextAndVersion newTextAndVersion, TreeAndVersion oldTreeAndVersion, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.DocumentState.IncrementallyParseTreeAsync(ValueSource`1 oldTreeSource, ValueSource`1 newTextSource, CancellationToken cancellationToken)<---
```

and ends with:
Failed exitCode=1, command=dotnet format -w {sln-name} -v diag

Several attempts resulted in the same result, including with the `--check` flag.

First guess is that this is an error within dotnet-format, as none of the files currently being processed have a method with a parameter named 'start'.

Dropping the version back to v3.0.4 resolved the issue for us but wanted to make sure this issue got logged.

**Comment by JoeRobich** [comment]
Hi @bishopsmove,

Thanks for reporting this issue. This does look like an issue with format. The change between the two versions is that the newer build tries to give file locations for the formatting errors.

Does the code that you were running this against happen to be open source? It would be very helpful to have a repro.

Thanks
-Joey

**Comment by RikkiGibson** [comment]
Edited the stack trace to improve readability.
