### ISSUE TITLE
System.InvalidOperationException: Sequence contains no elements

### ISSUE THREAD

**Issue by mristin** [dotnet/format#686]
Hi,
When running dotnet-format on our code base, I get a very cryptic exception (see below). Any idea what might be causing it? Could you maybe add a more informative error message? Or maybe this is a bug in dotnet-format?

The version of dotnet-format used was: 3.3.111304+7c8f67a570f5fde6a247704733d6742f93c0fa48, while the version of dotnet was 3.1.202.

Here is the exception:
```
Unhandled exception: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.CodeAnalysis.Tools.Program.Run(String folder, String workspace, String verbosity, Boolean dryRun, Boolean check, String include, String exclude, String report, IConsole console) in /_/src/Program.cs:line 110
   at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass3_0.<<InvokeAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseParseErrorReporting>b__16_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass3_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseSuggestDirective>b__7_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseDebugDirective>b__4_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseHelp>b__14_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseParseDirective>b__6_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<RegisterWithDotnetSuggest>b__17_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseExceptionHandler>b__5_0>d.MoveNext()
```

Specifying higher verbosity level did not change the error message.

**Comment by RikkiGibson** [comment]
@JoeRobich is this possibly fixed (or at least improved by) #658?

**Comment by JoeRobich** [comment]
Yes, the only thing holding up a new release on NuGet.org is moving to Rosyln .editorconfig support. The latest builds on MyGet have this change already.

**Comment by mristin** [comment]
I followed #658 to understand better the error. It turns out that there was no problem with MSBuild (it was installed correctly), but dotnet.exe was not on the PATH. So you probably want to add that check in #658?

**Comment by JoeRobich** [comment]
@mristin Thanks for the suggestion. This is one of those situations I didn't expect a dotnet global tool would be able to get into. I opened a PR that adds a check so that maybe it will be easier to troubleshoot next time.

**Comment by JoeRobich** [comment]
Closing as a check was added for being able to invoke `dotnet`.
