### ISSUE TITLE
Running as a build event

### ISSUE THREAD

**Issue by AnthonySteele** [dotnet/format#71]
If I open up a project properties in Visual Studio, go to "Build Events"
and add a pre-build or post-build step of "dotnet format"

Then the output that I get is:
```
1>------ Rebuild All started: Project: MyApp, Configuration: Debug Any CPU ------
1>MyApp -> C:\Code\MyApp\src\bin\Debug\netcoreapp2.2\MyApp.dll
1>Unhandled exception: System.AggregateException: An error occurred while writing to logger(s). (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
1>   at Microsoft.CodeAnalysis.Tools.Logging.SimpleConsoleLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in /_/src/Logging/SimpleConsoleLogger.cs:line 43
1>   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
1>   --- End of inner exception stack trace ---
1>   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
1>   at Microsoft.Extensions.Logging.Logger`1.Microsoft.Extensions.Logging.ILogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
1>   at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, EventId eventId, Exception exception, String message, Object[] args)
1>   at Microsoft.CodeAnalysis.Tools.CodeFormatter.CodeFormatter.FormatWorkspaceAsync(ILogger logger, String solutionOrProjectPath, Boolean isSolution, Boolean logAllWorkspaceWarnings, Boolean saveFormattedFiles, CancellationToken cancellationToken) in /_/src/CodeFormatter.cs:line 30
1>   at Microsoft.CodeAnalysis.Tools.CodeFormatter.Program.Run(String workspace, String verbosity, Boolean dryRun, IConsole console) in /_/src/Program.cs:line 68
1>   at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context)
1>   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass3_0.<<InvokeAsync>b__0>d.MoveNext()
1>--- End of stack trace from previous location where exception was thrown ---
1>   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseParseErrorReporting>b__16_0>d.MoveNext()
1>--- End of stack trace from previous location where exception was thrown ---
1>   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass3_0.<<UseVersionOption>b__0>d.MoveNext()
1>--- End of stack trace from previous location where exception was thrown ---
1>   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseSuggestDirective>b__7_0>d.MoveNext()
1>--- End of stack trace from previous location where exception was thrown ---
1>   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseDebugDirective>b__4_0>d.MoveNext()
1>--- End of stack trace from previous location where exception was thrown ---
1>   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseHelp>b__14_0>d.MoveNext()
1>--- End of stack trace from previous location where exception was thrown ---
1>   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseParseDirective>b__6_0>d.MoveNext()
1>--- End of stack trace from previous location where exception was thrown ---
1>   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<RegisterWithDotnetSuggest>b__17_0>d.MoveNext()
1>--- End of stack trace from previous location where exception was thrown ---
1>   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseExceptionHandler>b__5_0>d.MoveNext()
1>---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
1>   at Microsoft.CodeAnalysis.Tools.Logging.SimpleConsoleLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in /_/src/Logging/SimpleConsoleLogger.cs:line 43
1>   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)<---
1>
1>C:\Code\MyApp\src\MyApp.csproj(34,5): error MSB3073: The command "dotnet format" exited with code 1.
1>Done building project "MyApp.csproj" -- FAILED.
2>------ Rebuild All started: Project: MyApp.Tests, Configuration: Debug Any CPU ------
2>MyApp.Tests -> C:\Code\MyApp\test\bin\Debug\netcoreapp2.2\MyApp.Tests.dll
========== Rebuild All: 1 succeeded, 1 failed, 0 skipped ==========

```

If I'm doing the wrong thing here, what are other suggestions on how to run `format` very regularly,?

**Comment by jmarolf** [comment]
Can you try this on the pre-release version? I think we fixed this logging issue there

```cmd
dotnet install tool -g dotnet-format --version 3.0.4-prerelease.19178.2 --source https://dotnet.myget.org/F/format/api/v3/index.json
```

**Comment by AnthonySteele** [comment]
FYI, corrected commandline is
```
dotnet tool uninstall -g dotnet-format
dotnet tool install dotnet-format -g --version 3.0.4-prerelease.19178.2 --add-source https://dotnet.myget.org/F/format/api/v3/index.json
```

**Comment by AnthonySteele** [comment]
Confirmed, this works ok in `version 3.0.4-prerelease.19178.2`

**Comment by jmarolf** [comment]
@AnthonySteele 	alright I am going to close this issue as fixed
