### ISSUE TITLE
Error while converting vb code to C#

### ISSUE THREAD

**Issue by susan12-web** [dotnet/format#741]
Hi,

I am trying to convert vb code to C# using below conertor
https://marketplace.visualstudio.com/items?itemName=SharpDevelopTeam.CodeConverter.

But i am getting below error:

---------------------------
Code converter 8.1.6 - Visual Studio 16.0.29924.62
---------------------------
An error has occured during conversion - press Ctrl+C to copy the details: System.InvalidOperationException: Sequence contains no elements

   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)

   at ICSharpCode.CodeConverter.VsExtension.CodeConversion.<>c__DisplayClass24_0`1.<ConvertProjectUnhandled>b__2(Project p)

   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()

   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)

   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

   at ICSharpCode.CodeConverter.VsExtension.CodeConversion.<ConvertProjectUnhandled>d__24`1.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.GetResult(Int16 token)

   at ICSharpCode.CodeConverter.VsExtension.CodeConversion.<ConvertProjectUnhandled>d__24`1.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)

   at ICSharpCode.CodeConverter.VsExtension.CodeConversion.<WriteConvertedFilesAndShowSummaryAsync>d__16.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at ICSharpCode.CodeConverter.VsExtension.CodeConversion.<WriteConvertedFilesAndShowSummaryAsync>d__16.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at ICSharpCode.CodeConverter.VsExtension.CodeConversion.<>c__DisplayClass13_0`1.<<ConvertProjectsAsync>b__0>d.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__68.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at ICSharpCode.CodeConverter.VsExtension.CodeConversion.<ConvertProjectsAsync>d__13`1.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at ICSharpCode.CodeConverter.VsExtension.ConvertVBToCSCommand.<SolutionOrProjectMenuItemCallbackAsync>d__23.MoveNext()
---------------------------
OK   
---------------------------

Please help me in this.

**Comment by jmarolf** [comment]
I believe this issue should be filed on https://github.com/icsharpcode/CodeConverter
