### ISSUE TITLE
Wildcard folder throws unhandled exception

### ISSUE THREAD

**Issue by gewoonwoutje** [dotnet/format#973]
argument: `dotnet format ./**/* -f`

```sh
~\Workspace [dotnet-tool]> dotnet format ./**/* -f
  Formatting code files in workspace 'C:\Users\Wout\Workspace\**\*'.
Unhandled exception: System.ArgumentException: Folder 'C:\Users\Wout\Workspace\**\*' does not exist. (Parameter 'folderPath')
   at Microsoft.CodeAnalysis.Tools.Workspaces.FolderWorkspace.OpenFolder(String folderPath, SourceFileMatcher fileMatcher) in /_/src/Workspaces/FolderWorkspace.cs:line 36
   at Microsoft.CodeAnalysis.Tools.CodeFormatter.FormatWorkspaceAsync(FormatOptions formatOptions, ILogger logger, CancellationToken cancellationToken, Boolean createBinaryLog) in /_/src/CodeFormatter.cs:line 45
   at Microsoft.CodeAnalysis.Tools.Program.Run(String workspace, Boolean folder, Boolean fixWhitespace, String fixStyle, String fixAnalyzers, String verbosity, Boolean check, String[] include, String[] exclude, String report, Boolean includeGenerated, IConsole console) in /_/src/Program.cs:line 173
   at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__21_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__22_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__20_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__11_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
   ```
   ```sh
   ~\Workspace [dotnet-tool]> dotnet --version
5.0.103
~\Workspace  [dotnet-tool]> dotnet format --version
5.0.211103+b95e1694941ca2595941f1c9cd0d9727b6c53d43
```

**Comment by jmarolf** [comment]
This exception is coming from [here](https://github.com/dotnet/format/blob/d8ba1c35cffc6d5ec7dd052307fddef2d2feca6a/src/Workspaces/FolderWorkspace.cs#L36) and I think this is by-design. We could produce a better error message but you should be using `--include` or `--exclude` if you want to use globs.

**Comment by JoeRobich** [comment]
@gewoonwoutje Sorry the documentation isn't more clear. By default all code files are included when passing the `-f` flag. dotnet-format will also use the current working directory by default. The command for what you want is `dotnet format -f`.

**Comment by gewoonwoutje** [comment]
Although the documentation could be improved, I mainly filed this issue for the error handling. Generally, stacktraces should only show when the error is truely unknown and therefore unhandled. In this case, I think the error message `Folder C:\Users\Wout\Workspace\**\*' does not exist.` - without the stacktrace - already hints wildcards are not supported in this manner.
